name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date
        id: date
        run: |
            echo "date=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_ENV
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cluster_algebras.tex
      - name: Upload PDF file to new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.date }}
          commit: "main"
          name: ${{ env.date }}
          artifacts: "cluster_algebras.pdf"
