name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
            echo "{date}={$(date +'%Y-%m-%d--%H-%M')}" >> $GITHUB_STATE
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cluster_algebras.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF-${{ env.date }}
          path: cluster_algebras.pdf
